#TEX = pdflatex
#BIB = bibtex
#GS = gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite 

#PAPER = Frissell-MSTID
#BIBFILE = temp.bib
#
#all: $(PAPER).tex
#	$(TEX) -draftmode $(PAPER).tex
#	$(BIB) $(PAPER).aux
#	$(TEX) -draftmode $(PAPER).tex
#	$(TEX) $(PAPER).tex
#
#short: $(PAPER).tex
#	$(TEX) $(PAPER).tex
#
#view: $(PAPER).pdf
#	open $(PAPER).pdf
#
#spell::
#	ispell -t *.tex

clean::
	rm -fv *.pyc
